@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
AddSystemTag("bgcolor", $bgColor="#ed0fd3ff")

Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(аналитик, "Аналитик", "Работа с BI-системой")
Person(фермер, "Фермер", "Использует мобильное приложение",$tags="bgcolor")

System_Boundary(платформа, "АгроФерма Х - Цифровая платформа") {
    
    System(данные, "Хранилища данных","Сырые или структурированные данные") 
    System(аналитика, "Аналитический модуль",  "Анализ эффективности")
    System(ui, "Взаимодействие с системой", "пользовательский интерфейс")
    Container_Boundary(подсистема_фермы,"Подсистема фермы"){
        System(модуль_фермы, "Мониторинг фермы", $tags="bgcolor")
        System(ферма_iot_платформа, "IoT платформа для фермы", $tags="bgcolor") 
        System(ферма_брокер, "брокер для фермы", $tags="bgcolor") 

}

      
}

' === Взаимосвязи ===
Rel(ui, брокер, "отчеты")
Rel(брокер, данные, "Хранение данных")
Rel(ui, данные, "Управление и аналитика")

' === Взаимосвязи подсистемы фермы ===
Rel(модуль_фермы, ферма_iot_платформа, "передает данные")
Rel(ферма_брокер, данные, "сохраняет данные")
Rel(ферма_iot_платформа, ферма_брокер, "публикует данные")
Rel(ui, подсистема_фермы, "использует")
Rel(аналитика, данные, "Использует")

' === Взаимосвязи пользователей и сервисов===
Rel(директор, ui, "Использует")
Rel(аналитик, аналитика, "Анализирует")
Rel(фермер, ui, "Использует")

@enduml