@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
AddSystemTag("bgcolor", $bgColor="#ed0fd3ff")

Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(агроном, "Агроном", "Использует мобильное приложение")
Person(тепличник, "Тепличный комплекс", "Управление теплицами")
Person(механик, "Механик", "Мониторинг техники")
Person(аналитик, "Аналитик", "Работа с BI-системой")
Person(фермер, "Фермер", "Использует мобильное приложение",$tags="bgcolor")

System_Boundary(платформа, "АгроПром Х - Цифровая платформа") {
    
    System(erp, "ERP система (1С:Агро)", "1С", "Финансы, склад, кадры")
    System(тепличные_системы, "Тепличные комплексы") 
    System(брокер, "Брокер сообщений", "Apache Kafka")
    System(iot_платформа, "IoT платформа") 
    System(полевые_данные, "Данные с полей")
    System(управление_техникой, "Управление техникой") 
    System(данные, "Хранилища данных","Сырые или структурированные данные") 
    System(аналитика, "Аналитический модуль",  "Анализ эффективности")
    System(ui, "Взаимодействие с системой", "пользовательский интерфейс")
      
}
Container_Boundary(подсистема_фермы,"Подсистема фермы"){
System(модуль_фермы, "Сервис управления фермой", $tags="bgcolor")
System(ферма_iot_платформа, "IoT платформа для фермы", $tags="bgcolor") 
System(ферма_брокер, "брокер для фермы", $tags="bgcolor") 

}

' === Взаимосвязи ===
Rel(тепличные_системы, брокер, "публикует данные")

Rel(полевые_данные, iot_платформа, "передает данные")
Rel(iot_платформа, брокер, "Публикует данные")
Rel(ui, брокер, "отчеты")
Rel(брокер, управление_техникой, "Поток задач")
Rel(брокер, данные, "Хранение данных")
Rel(управление_техникой, erp, "Служебная инф-ия")
Rel(ui, данные, "Управление и аналитика")

' === Взаимосвязи подсистемы фермы ===
Rel(модуль_фермы, ферма_iot_платформа, "передает данные")
Rel(модуль_фермы, ферма_брокер, "публикует данные")
Rel(модуль_фермы, данные, "сохраняет данные")
Rel(модуль_фермы, данные, "сохраняет данные")
Rel(ui, подсистема_фермы, "использует")

' === Взаимосвязи пользователей и сервисов===
Rel(директор, ui, "Использует")
Rel(агроном, ui, "Использует")
Rel(механик, iot_платформа, "Мониторит")
Rel(тепличник, iot_платформа, "Управляет")
Rel(аналитик, аналитика, "Анализирует")
Rel(агроном, ui, "Мониторит")
Rel(механик, подсистема_фермы, "Мониторит")

Rel(фермер, ui, "Использует")

@enduml