@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
AddSystemTag("bgcolor", $bgColor="#ed0fd3ff")

Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(аналитик, "Аналитик", "Работа с BI-системой")
Person(фермер, "Фермер", "Использует мобильное приложение",$tags="bgcolor")

System_Boundary(платформа, "АгроФерма Х - Цифровая платформа") {
    
    System(брокер, "Брокер сообщений", "Apache Kafka")
    System(iot_платформа, "IoT платформа") 
    System(данные, "Хранилища данных","Сырые или структурированные данные") 
    System(аналитика, "Аналитический модуль",  "Анализ эффективности")
    System(ui, "Взаимодействие с системой", "пользовательский интерфейс")
    System(модуль_фермы, "Новый фермерский модуль",$tags="bgcolor")
      
}

' === Взаимосвязи ===
Rel(модуль_фермы, iot_платформа, "публикует данные")
Rel(iot_платформа, брокер, "Публикует данные")
Rel(ui, брокер, "отчеты")
Rel(брокер, данные, "Хранение данных")
Rel(ui, данные, "Управление и аналитика")
Rel(аналитика, данные, "Использует")


' === Взаимосвязи пользователей и сервисов===
Rel(директор, ui, "Использует")
Rel(аналитик, аналитика, "Анализирует")
Rel(фермер, ui, "Использует")



@enduml