@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml




' === Участники ===
Person(фермер1, "Фермер 1", "Пользователь платофрмы")
Person(фермер2, "Фермер 2", "Пользователь платофрмы")

System_Boundary(платформа, "Ферма Х - Цифровая платформа") 

System_Boundary(ферма1, "Датчики фермы 1") 
System_Boundary(ферма2, "Датчики фермы 2") 
System_Boundary(ферма3, "Датчики фермы 3") 



' === Взаимосвязи ===
Rel(фермер1, платформа, "Использует")
Rel(фермер2, платформа, "Использует")
Rel(ферма1, фермер1, "Регистрирует данные для фермы1")
Rel(ферма3, фермер1, "Регистрирует данные для фермы3")
Rel(ферма2, фермер2, "Регистрирует данные для фермы2")

